### ISSUE TITLE
Замечания к лабораторной

### ISSUE THREAD

**Issue by rredbird66** [mEmmEmmEm/lab2pzrl_Manyakhina#1]
1. Некорректно работает побитовая инверсия
![изображение](https://github.com/mEmmEmmEm/lab2pzrl_Manyakhina/assets/36138085/52baee7c-e672-4a5b-b982-bc2a176952c3)
2. Почему-то не считается hex
![изображение](https://github.com/mEmmEmmEm/lab2pzrl_Manyakhina/assets/36138085/a90997e7-0d6c-43fc-9819-5e691833286e)
3. В Makefile не используются переменные, а должны.
4. start не добавлен в .gitignore
![изображение](https://github.com/mEmmEmmEm/lab2pzrl_Manyakhina/assets/36138085/6df5a30f-9acb-4fdc-ab05-49b39c9d5d01)

**Comment by mEmmEmmEm** [comment]
исправила ^_^

**Comment by rredbird66** [comment]
1. Дублирование #include в заголовочных файлах и файлах исходного кода.
2. Как правило, define в HEADER_GUARDS делается совпадающим с именем файла. Т.е. в файле func2.h он должен называться FUNC2_H и аналогично для других. Это позволяет не создавать дополнительной путаницы.

**Comment by mEmmEmmEm** [comment]
исправила

**Comment by rredbird66** [comment]
Лабораторная работа 2 зачтена.
